package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*
import jetbrains.buildServer.configs.kotlin.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'Project_HttpsGithubComAndrewmaltTestTcNewGitRefsHeadsMain'
in the project with id = 'Project', and delete the patch script.
*/
create(RelativeId("Project"), GitVcsRoot({
    id("Project_HttpsGithubComAndrewmaltTestTcNewGitRefsHeadsMain")
    name = "https://github.com/andrewmalt/test-tc-new.git#refs/heads/main"
    url = "https://github.com/andrewmalt/test-tc-new.git"
    branch = "refs/heads/main"
    branchSpec = "refs/heads/*"
}))

